apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui
spec:
  selector:
    matchLabels:
      app: todo-ui
  replicas: 2
  template:
    metadata:
      labels:
        app: todo-ui
    spec:
      containers:
      - name: todo-ui
        image: mdcontainerregistry.azurecr.io/todoui-api:v2
        ports:
        - containerPort: 80
